name: ESP32 Builder

on:
  push:
    branches: [ esp32 ]
  pull_request:
    branches: [ esp32 ]

jobs:
  builder:
    name: Builder for test ESP32 project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'latest'

      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py reconfigure
          idf.py app
          idf.py size
